on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/copilot-setup-steps.yml'
env:
  ACTIONS_CACHE_VERSION: 2

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Install ClojureCLR and cljr
        run: |
          dotnet tool install --global Clojure.Main --version 1.12.3-alpha3
          dotnet tool install --global Clojure.Cljr --version 0.1.0-alpha8
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          which Clojure.Main || echo "Clojure.Main not in PATH"
          which cljr || echo "cljr not in PATH"
          cljr --version

      - name: Restore dependency cache
        id: cache-deps
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ env.ACTIONS_CACHE_VERSION }}-deps-${{ hashFiles('**/deps.edn', '**/deps-clr.edn') }}

      - name: Debug cache outputs
        run: |
          echo "cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}"
          echo "cache-matched-key: ${{ steps.cache-deps.outputs.cache-matched-key }}"

      - name: Download dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          cljr -A:test -Stree

      - name: Save dependency cache
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ env.ACTIONS_CACHE_VERSION }}-deps-${{ hashFiles('**/deps.edn', '**/deps-clr.edn') }}
